# build-system generated configuration file
# feel free to update values here, it could be fun!
# if things break, then you are doing great!
--shared-library-ext: .dll
compilers:
  c++:
    command: cl
    function: c++
    options:
    - /nologo
    - /c
    - /O2
    - /EHsc
    output_switch: '/Fo:'
    path_switch: /I
    paths:
    - ./src/
    - C:\Python27\include
linkers:
  c++-exe:
    command: link
    function: c++-exe
    options:
    - /nologo
    output_switch: '/out:'
    path_switch: '/LIBPATH:'
    paths:
    - C:\Python27\libs
    post_options: []
  c++-lib:
    command: link
    function: c++-lib
    options:
    - /nologo
    - /DLL
    output_switch: '/out:'
    path_switch: '/LIBPATH:'
    paths:
    - C:\Python27\libs
    post_options: []
builders:
  c++-exe:
    compiler.function: c++
    linker.function: c++-exe
  c++-lib:
    compiler.function: c++
    linker.function: c++-lib
